name: SonarCloud Analysis

on:
  push:
    branches:
      - '*'

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: SonarCloud Scan
        run: |
          ./gradlew sonarqube -Dsonar.projectKey=alu0101325781_Finalproject-LyDH -Dsonar.organization=alu0101325781 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}